import type { Metadata } from "next";
import MobileBlocker from "@/components/MobileBlocker";
import PageTransition from "@/components/PageTransition";
import "../styles/globals.css";
import localFont from "next/font/local";

const myFont = localFont({
    src: [
        {
            path: "../public/fonts/Lausanne-300.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../public/fonts/Lausanne-500.woff2",
            weight: "500",
            style: "normal",
        },
    ],
    variable: "--font-myfont",
});

export const metadata: Metadata = {
    title: "K72",
    description: "Generated by Taimoor Khan",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${myFont.variable} antialiased`}>
                <MobileBlocker>
                    <PageTransition>{children}</PageTransition>
                </MobileBlocker>
            </body>
        </html>
    );
}
